import type { Word } from '@/types'

/** 测试用迷你词库：手写入门词已移除，测试统一使用本夹具，避免依赖真实词库数据 */
export const testWords: Word[] = [
  {
    id: 't1',
    word: 'bonjour',
    phonetic: '/bɔ̃ʒuʁ/',
    pos: 'interj.',
    meaning: '你好',
    example: 'Bonjour !',
    exampleZh: '你好！',
    level: 'A1',
    tags: ['问候'],
  },
  {
    id: 't2',
    word: 'merci',
    phonetic: '/mɛʁsi/',
    pos: 'n.m.',
    meaning: '谢谢',
    example: 'Merci !',
    exampleZh: '谢谢！',
    level: 'A1',
    tags: ['礼貌'],
  },
  {
    id: 't3',
    word: 'salut',
    phonetic: '/saly/',
    pos: 'interj.',
    meaning: '你好；再见',
    example: 'Salut !',
    exampleZh: '嗨！',
    level: 'A1',
    tags: ['问候'],
  },
  {
    id: 't4',
    word: 'oui',
    phonetic: '/wi/',
    pos: 'adv.',
    meaning: '是',
    example: 'Oui.',
    exampleZh: '是的。',
    level: 'A1',
    tags: ['基础'],
  },
  {
    id: 't5',
    word: 'non',
    phonetic: '/nɔ̃/',
    pos: 'adv.',
    meaning: '不',
    example: 'Non.',
    exampleZh: '不。',
    level: 'A1',
    tags: ['基础'],
  },
  {
    id: 't6',
    word: 'maison',
    phonetic: '/mɛzɔ̃/',
    pos: 'n.f.',
    meaning: '房子',
    example: "Ma maison est grande.",
    exampleZh: '我的房子很大。',
    level: 'A1',
    tags: ['生活'],
  },
  {
    id: 't7',
    word: 'ami',
    phonetic: '/ami/',
    pos: 'n.m.',
    meaning: '朋友',
    example: 'C\'est mon ami.',
    exampleZh: '这是我的朋友。',
    level: 'A1',
    tags: ['生活'],
  },
  {
    id: 't8',
    word: 'école',
    phonetic: '/ekɔl/',
    pos: 'n.f.',
    meaning: '学校',
    example: "Je vais à l'école.",
    exampleZh: '我去学校。',
    level: 'A1',
    tags: ['生活'],
  },
  {
    id: 't9',
    word: 'manger',
    phonetic: '/mɑ̃ʒe/',
    pos: 'v.t.',
    meaning: '吃',
    example: 'Je mange.',
    exampleZh: '我吃饭。',
    level: 'A1',
    tags: ['动词'],
  },
  {
    id: 't10',
    word: 'aimer',
    phonetic: '/eme/',
    pos: 'v.t.',
    meaning: '喜欢',
    example: "J'aime le français.",
    exampleZh: '我喜欢法语。',
    level: 'A1',
    tags: ['动词'],
  },
]
